### ISSUE TITLE
Downloader Prematurely Stopping

### ISSUE THREAD

**Issue by nzkzero** [Zogzer/BloodCatTrawler#1]
First of all, I'd like to thank you Zogzor for creating the BloodCat Trawler. I use it every day.

The trawler stops downloading every few hours for me. (The progress bar freezes.)
Typically, the trawler successfully downloads roughly 100 songs before freezing.

Clicking the stop and start button will cause the program to function normally for another few hours, before freezing again.

The most simple solution I can think of would be to have the trawler automatically stop/resume itself occasionally.

**Comment by Yen** [comment]
Hey, I will look into it but it would be nice if you could give me some more info on the matter. Things like your OS version and if your internet is stable or cuts out. Also a screen shot of the client when this occurs would be appreciated if possible, Thanks!

**Comment by nzkzero** [comment]
I'm running Windows 10 Home 64-bit.
I have a 10mbps DSL connection, which is fairly slow, but stable nonetheless.

Screenshot as you requested:

![screenshot](https://cloud.githubusercontent.com/assets/18353625/14397881/f8dd479a-fd94-11e5-9990-54ae237bfb17.png)

**Comment by Yen** [comment]
It would seem there is no way that a freeze like this could occur as a result of problems in client code, my guess is that this is a result of bloodcat download servers simply stopping to send data without terminating the connection correctly, why this would be is unknown. As this is not something I would deem an bug and simply how internet protocols work I cannot do much to fix it. I am closing this now as it is not related to code in this project but if you come across any relations (things like specific songs causing this or only on certain settings) you can still comment on this thread and I can take another look.
