### ISSUE TITLE
BloodCat added a captcha

### ISSUE THREAD

**Issue by ValliereMagic** [Zogzer/BloodCatTrawler#2]
![untitled](https://cloud.githubusercontent.com/assets/20320239/24324506/2e75b86e-115e-11e7-84a1-4f9de3a4d6d4.png)

when your program is querying the download expecting a stream of data, it is not getting the song.
being unable to download any songs, it acts like this...
![untitled](https://cloud.githubusercontent.com/assets/20320239/24324528/928f5abc-115e-11e7-9637-f2a119a1479a.png)
![untitled1](https://cloud.githubusercontent.com/assets/20320239/24324531/9736767c-115e-11e7-89b8-f580feb52f1c.png)
flashing between these two states constantly.
However... the captcha is only displayed if you don't have an active session, as you can download all you want after you solve the captcha once. (spitballing here) Maybe if you add a request to the first song the system is attempting to download, render the captcha page, and then get the user to solve the captcha. Maybe this framework will help you get a valid session https://en.wikipedia.org/wiki/Chromium_Embedded_Framework. Hope this helps...
Cheers 
           ~Valliere

**Comment by Yen** [comment]
Hey Valliere, thanks for your report. If this is the case and bloodcat have added a captcha then I think its evident that this kind of tool is not welcome. I am going to add a notice to the project that it will no longer work.
Out of respect for the wishes of the owners of the bloodcat service I will not be working on a solution to this. If however you or anyone else wishes to implement this feature, feel free to fork!, I would love to see a headless browser solution like the one you suggest. 👍
